### ISSUE TITLE
Why wrap a node module that does exactly this?

### ISSUE THREAD

**Issue by guidobouman** [hashdog/node-identicon-github#1]
Why would you wrap [sehrgut/node-retricon](https://github.com/sehrgut/node-retricon) when that package does exactly the same? You even copied his documentation.

Or am I missing something?

**Comment by colkito** [comment]
Hi @guidobouman,
We made the "wrap" to use this great module in our projects. I noticed that the original module ([sehrgut/node-retricon](https://github.com/sehrgut/node-retricon)) was (finally) updated 3 days ago. Updating  canvas dependency. 
We tried to contact the owner (without responses in Jul 2015) to suggest this change (in same way that another PRs from 2014).

The project was abandoned from  2013. That is the main reason.

Best.

**Comment by guidobouman** [comment]
So, you basicly forked the repo? (But without actually forking it.)

Then I misunderstood the description. I thought you wrapped the original repo and used it as a dependency.

Pro tip: use the fork button on GitHub. That leaves a traceable history, and makes it easier for the original author to pull in your changes.
